# -*- coding: utf-8 -*-
"""LGBMFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4vtKO8ZOdQrWX3vlM0t6PYKmOwUPuAY
"""

LGBM FE + normalize edilmiş dataset

import pandas as pd
import numpy as np
import time
from sklearn.model_selection import train_test_split
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from google.colab import drive
drive.mount('/content/drive')

test_size = 0.2
dosya_yolu = "/content/All_Combined.csv"
data = pd.read_csv(dosya_yolu, parse_dates=["Time"])

gr = data.groupby("Location", group_keys=False)
data["Power_lag1"] = gr["Power"].shift(1)
data["Power_lag24"] = gr["Power"].shift(24)
data["Power_rollmean3"] = gr["Power"].shift(1).rolling(3).mean()
data["Power_rollmeansdt3"] = gr["Power"].shift(1).rolling(24).mean()

data["hour"] = data["Time"].dt.hour
data["dayofweek"] = data["Time"].dt.dayofweek
data["month"] = data["Time"].dt.month

X = data.drop(columns=["Time", "Power"]).copy()
y = data["Power"].copy()

obje_kolonlar = X.select_dtypes(include=["object"])
if len(obje_kolonlar) > 0:
    X[obje_kolonlar.columns] = X[obje_kolonlar.columns].apply(pd.to_numeric, errors="coerce")

X = X.replace([np.inf, -np.inf], np.nan)

# Tüm feature'ları dolu olan satırlar
maske = X.notna().all(axis=1) & y.notna()
X = X.loc[maske].reset_index(drop=True)
y = y.loc[maske].reset_index(drop=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=test_size, shuffle=False
)

print(f"Eğitim seti boyutu (X_train): {X_train.shape[0]}")
print(f"Test seti boyutu (X_test): {X_test.shape[0]}\n")

lgbm = LGBMRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="regression",
    random_state=42,
    n_jobs=-1
)

start_time = time.time()
lgbm.fit(X_train, y_train)
end_time = time.time()
print(f"Eğitim tamamlandı. Süre: {end_time - start_time: .2f} saniye")

y_pred_lgbm = lgbm.predict(X_test)
mae_lgbm = mean_absolute_error(y_test, y_pred_lgbm)
rmse_lgbm = np.sqrt(mean_squared_error(y_test, y_pred_lgbm))
r2_lgbm = r2_score(y_test, y_pred_lgbm)

print("\n LGBM Model Metrikleri (AllCombined + FE) ")
print(f"MAE (Ort. Mutlak Hata):  {mae_lgbm:.6f}")
print(f"RMSE (K.K. Ort. Hata):   {rmse_lgbm:.6f}")
print(f"R² (Belirleme Katsayısı): {r2_lgbm:.4f}")

"""LGBM + NOT FE + normalize edilmiş dataset


"""

import pandas as pd
import numpy as np
import time
from sklearn.model_selection import train_test_split
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from google.colab import drive
drive.mount('/content/drive')

test_size = 0.2
dosya_yolu = "/content/All_Combined.csv"
data = pd.read_csv(dosya_yolu, parse_dates=["Time"])

X = data.drop(columns=["Time", "Power"]).copy()
y = data["Power"].copy()

obje_kolonlar = X.select_dtypes(include=["object"])
if len(obje_kolonlar) > 0:
    X[obje_kolonlar.columns] = X[obje_kolonlar.columns].apply(pd.to_numeric, errors="coerce")

X = X.replace([np.inf, -np.inf], np.nan)

# Tüm feature'ları dolu olan satırlar
maske = X.notna().all(axis=1) & y.notna()
X = X.loc[maske].reset_index(drop=True)
y = y.loc[maske].reset_index(drop=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=test_size, shuffle=False
)

print(f"Eğitim seti boyutu (X_train): {X_train.shape[0]}")
print(f"Test seti boyutu (X_test): {X_test.shape[0]}\n")

lgbm = LGBMRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="regression",
    random_state=42,
    n_jobs=-1
)

start_time = time.time()
lgbm.fit(X_train, y_train)
end_time = time.time()
print(f"Eğitim tamamlandı. Süre: {end_time - start_time: .2f} saniye")

y_pred_lgbm = lgbm.predict(X_test)
mae_lgbm = mean_absolute_error(y_test, y_pred_lgbm)
rmse_lgbm = np.sqrt(mean_squared_error(y_test, y_pred_lgbm))
r2_lgbm = r2_score(y_test, y_pred_lgbm)

print("\n LGBM Model Metrikleri (AllCombined – FE YOK)")
print(f"MAE (Ort. Mutlak Hata):  {mae_lgbm:.6f}")
print(f"RMSE (K.K. Ort. Hata):   {rmse_lgbm:.6f}")
print(f"R² (Belirleme Katsayısı): {r2_lgbm:.4f}")

"""LGBM + FE + direkt SCADA türbin verisinin meteorolojik verilerle çeşitlendirilmiş hali



"""

from google.colab import drive
drive.mount('/content/drive')

dosya_yolu = "/content/T1_merged_meteo.csv"

df = pd.read_csv(dosya_yolu)
print("Ham veri şekli:", df.shape)
print("Sütunlar:", df.columns.tolist())

df["Time"] = pd.to_datetime(df["Time"])
df = df.sort_values("Time").reset_index(drop=True)

data = df.copy()

# İsimleri standardize et
data = data.rename(columns={
    "LV ActivePower (kW)": "Power",
    "Date/Time": "Time"
})

data["Time"] = pd.to_datetime(data["Time"])
print("Başlangıç shape:", data.shape)

# Start/stop gürültüsü filtresi
data = data[data["Power"] > 50]
print("Power>50 filtresi sonrası:", data.shape)

# Power türev ve lag'ler
data["dPower"]      = data["Power"].diff()
data["Power_lag1"]  = data["Power"].shift(1)
data["Power_lag6"]  = data["Power"].shift(6)
data["Power_lag24"] = data["Power"].shift(24)

# Rolling ortalama / std
data["Power_roll6"] = data["Power"].shift(1).rolling(6).mean()
data["Power_roll12"] = data["Power"].shift(1).rolling(12).mean()
data["Power_rollstd6"] = data["Power"].shift(1).rolling(6).std()

# Rüzgar hızı feature'ları
if "Wind Speed (m/s)" in data.columns:
    data["dWind"] = data["Wind Speed (m/s)"].diff()
    data["Wind_rollmean3"] = data["Wind Speed (m/s)"].shift(1).rolling(3).mean()
    data["Wind_rollstd3"] = data["Wind Speed (m/s)"].shift(1).rolling(3).std()
    data["Wind3"] = data["Wind Speed (m/s)"] ** 3

# Rüzgar yönü sin/cos
if "Wind Direction (°)" in data.columns:
    data["wind_sin"] = np.sin(np.deg2rad(data["Wind Direction (°)"]))
    data["wind_cos"] = np.cos(np.deg2rad(data["Wind Direction (°)"]))

# Zaman feature'ları
data["hour"]      = data["Time"].dt.hour
data["dayofweek"] = data["Time"].dt.dayofweek
data["month"]     = data["Time"].dt.month
data["dayofyear"] = data["Time"].dt.dayofyear

# ERA5 meteo feature'ları
if "windspeed_100m" in data.columns:
    data["era_ws100"]   = data["windspeed_100m"]
    data["era_ws100_3"] = data["windspeed_100m"] ** 3

if "windspeed_10m" in data.columns:
    data["era_ws10"] = data["windspeed_10m"]

if "winddirection_10m" in data.columns:
    data["era_wd_sin"] = np.sin(np.deg2rad(data["winddirection_10m"]))
    data["era_wd_cos"] = np.cos(np.deg2rad(data["winddirection_10m"]))

if "windgusts_10m" in data.columns:
    data["era_gust"] = data["windgusts_10m"]

if "temperature_2m" in data.columns:
    data["era_temp2"] = data["temperature_2m"]

if "relativehumidity_2m" in data.columns:
    data["era_rh2"] = data["relativehumidity_2m"]

if "dewpoint_2m" in data.columns:
    data["era_dew2"] = data["dewpoint_2m"]

# Hava yoğunluğu
R = 287.05
if "pressure_msl" in data.columns and "temperature_2m" in data.columns:
    data["air_density"] = (data["pressure_msl"] * 100) / (R * (data["temperature_2m"] + 273.15))

# Tamamen NaN kolonları temizle
data = data.dropna(axis=1, how="all")

# Lag/rolling nedeniyle ilk örnekleri at
data = data.iloc[24:].copy()

# Kalan NaN'leri satır bazında temizle
data = data.dropna().reset_index(drop=True)

print("FE sonrası veri şekli:", data.shape)
print("Kalan kolon sayısı:", len(data.columns))
print("Kolonlar:", data.columns.tolist())

hedef_sutun = "Power"
tarih_sutun = "Time"

ozellik_sutunlar = [c for c in data.columns if c not in [hedef_sutun, tarih_sutun]]

X = data[ozellik_sutunlar].values
y = data[hedef_sutun].values

n = len(data)
train_end = int(n * 0.70)
val_end   = int(n * 0.85)

X_train, y_train = X[:train_end], y[:train_end]
X_val,   y_val   = X[train_end:val_end], y[train_end:val_end]
X_test,  y_test  = X[val_end:], y[val_end:]

print(f"Toplam örnek sayısı: {n}")
print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")
print("Özellik sayısı:", X_train.shape[1])

lgbm = LGBMRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="regression",
    random_state=42,
    n_jobs=-1
)

start_time = time.time()
lgbm.fit(X_train, y_train)
end_time = time.time()
print(f"Eğitim tamamlandı. Süre:{end_time - start_time: .2f} saniye")

y_pred = lgbm.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5
r2 = r2_score(y_test, y_pred)

print(" LGBM Sonuçları (T1 + FE)")
print(f"MAE : {mae:.3f}")
print(f"RMSE: {rmse:.3f}")
print(f"R²  : {r2:.4f}")

def evaluate(name, y_true, y_pred):
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    r2   = r2_score(y_true, y_pred)
    print(f"{name:<15} → MAE: {mae:.3f}, RMSE: {rmse:.3f}, R2: {r2:.4f}")

from lightgbm import LGBMRegressor

base_params = dict(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=-1,      # LGBM'de -1 = sınırsız (ya da 6, 8 vs)
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42,
    n_jobs=-1
)

lgbm_q10 = LGBMRegressor(
    objective="quantile",
    alpha=0.1,
    **base_params
)

lgbm_q50 = LGBMRegressor(
    objective="quantile",
    alpha=0.50,
    **base_params
)

lgbm_q90 = LGBMRegressor(
    objective="quantile",
    alpha=0.9,
    **base_params
)

lgbm_q10.fit(X_train, y_train)
lgbm_q50.fit(X_train, y_train)
lgbm_q90.fit(X_train, y_train)

y_q10 = lgbm_q10.predict(X_test)
y_q50 = lgbm_q50.predict(X_test)
y_q90 = lgbm_q90.predict(X_test)

inside_band = (y_test >= y_q10) & (y_test <= y_q90)
coverage = inside_band.mean() * 100
print(f"%90 bandının gerçek kapsaması (LGBM): %{coverage:.2f}")

"""LGBM + NOT FE + direkt SCADA türbin verisinin meteorolojik verilerle çeşitlendirilmiş hali"""

import numpy as np
import pandas as pd

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from lightgbm import LGBMRegressor

df = pd.read_csv("/content/T1_merged_meteo.csv")

df["Time"] = pd.to_datetime(df["Time"], errors="coerce")

print("Veri şekli:", df.shape)
print(df.head())

df = df.rename(columns={
    "LV ActivePower (kW)": "Power",
    "ActivePower": "Power",
    "Date/Time": "Time",
    "DATE_TIME": "Time"
})

hedef_sutun = "Power"
tarih_sutun = "Time"

X = df.drop(columns=[tarih_sutun, hedef_sutun]).copy()
y = df[hedef_sutun].copy()

print("Başlangıç X shape:", X.shape)

# Tamamen NaN kolonları sil
X = X.dropna(axis=1, how="all")
print("Tamamen NaN kolonlar temizlendi. X shape:", X.shape)

# INF → NaN
X = X.replace([np.inf, -np.inf], np.nan)

# Çok fazla NaN içeren kolonları sil (ör: %40'tan fazla eksik)
threshold = 0.40
column_valid_ratio = X.notna().mean()
cols_to_drop = column_valid_ratio[column_valid_ratio < (1 - threshold)].index.tolist()
if len(cols_to_drop) > 0:
    print("Aşırı eksik kolonlar silindi:", cols_to_drop)
    X = X.drop(columns=cols_to_drop)

print("Eksik kolon temizliği sonrası X shape:", X.shape)

# Satır bazlı NaN temizliği
X = X.dropna().reset_index(drop=True)
y = y.loc[X.index]  # Y'yi hizala

print("Son temizlenmiş X shape:", X.shape)
print("Son temizlenmiş y shape:", y.shape)

n = len(X)
train_end = int(n * 0.70)
val_end   = int(n * 0.85)

X_train, y_train = X.iloc[:train_end].values, y.iloc[:train_end].values
X_val,   y_val   = X.iloc[train_end:val_end].values, y.iloc[train_end:val_end].values
X_test,  y_test  = X.iloc[val_end:].values, y.iloc[val_end:].values

print(f"Toplam örnek sayısı: {n}")
print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")
print("Özellik sayısı:", X_train.shape[1])

lgbm = LGBMRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="regression",
    random_state=42,
    n_jobs=-1
)

start_time = time.time()
lgbm.fit(X_train, y_train)
end_time = time.time()
print(f"Eğitim tamamlandı. Süre:{end_time - start_time: .2f} saniye")

y_pred = lgbm.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5
r2 = r2_score(y_test, y_pred)

print(" LGBM Sonuçları (T1 – FE YOK)")
print(f"MAE : {mae:.3f}")
print(f"RMSE: {rmse:.3f}")
print(f"R²  : {r2:.4f}")

def evaluate(name, y_true, y_pred):
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    r2   = r2_score(y_true, y_pred)
    print(f"{name:<15} → MAE: {mae:.3f}, RMSE: {rmse:.3f}, R2: {r2:.4f}")

# VALIDATION
y_val_pred = lgbm.predict(X_val)
print("=== VALIDATION SONUÇLARI (LGBM, FE YOK) ===")
evaluate("LGBM (val)", y_val, y_val_pred)

# TEST
y_test_pred = lgbm.predict(X_test)
print("\n=== TEST SONUÇLARI (LGBM, FE YOK) ===")
evaluate("LGBM (test)", y_test, y_test_pred)

from lightgbm import LGBMRegressor

base_params = dict(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=-1,      # LGBM'de -1 = sınırsız (ya da 6, 8 vs)
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42,
    n_jobs=-1
)

lgbm_q10 = LGBMRegressor(
    objective="quantile",
    alpha=0.1,
    **base_params
)

lgbm_q50 = LGBMRegressor(
    objective="quantile",
    alpha=0.50,
    **base_params
)

lgbm_q90 = LGBMRegressor(
    objective="quantile",
    alpha=0.9,
    **base_params
)

lgbm_q10.fit(X_train, y_train)
lgbm_q50.fit(X_train, y_train)
lgbm_q90.fit(X_train, y_train)

y_q10 = lgbm_q10.predict(X_test)
y_q50 = lgbm_q50.predict(X_test)
y_q90 = lgbm_q90.predict(X_test)

inside_band = (y_test >= y_q10) & (y_test <= y_q90)
coverage = inside_band.mean() * 100
print(f"%90 bandının gerçek kapsaması (LGBM): %{coverage:.2f}")